### ISSUE TITLE
Tapping Sign-in button does nothing

### ISSUE THREAD

**Issue by burkybang** [crypticplank/flappybird#28]
After updating to 4.0.5, I noticed I wasn't signed in anymore. Tapping on the Sign-in button isn't doing anything. Same result after restarting the app

https://user-images.githubusercontent.com/927886/136631647-2a32955f-9f40-449d-998e-2baf3dcaa65a.MOV

**Comment by BrandonPlank** [comment]
Yeah, so this is a bug. To fix it, fully remove the app and reinstall.

**Comment by burkybang** [comment]
Uninstalling/reinstalling worked. Thanks.

I've never been able to get the one from your Cydia repo to work. It always crashes at launch. I have to install the ipa via AppSync.

**Comment by shadoez** [comment]
I’ve also experienced this, reinstalling did not work. I’ve tried wiping data in Apps Manager & clearing the app’s cache.

Also when I try to tap the Leaderboard button it just freezes. 

Installing deb file results in crash upon startup.

**Comment by BrandonPlank** [comment]
The leaderboard issue is because the server is offline right not.

Check the official team twitter

@FlappyBirdRev

**Comment by BrandonPlank** [comment]
And I would refrain Installing the app from my cydia repo until I figure out what's wrong.

**Comment by 1345abozR** [comment]
- 

> 1678

- [ ]   #@**_2345

- Duplicate of [#_**[](url)]([url](

> url

))

**Comment by 1345abozR** [comment]
>

**Comment by 1345abozR** [comment]
# @shadoez 

- [ ] 

> 

> **__**

**Comment by 1345abozR** [comment]
Gyhhr654>764

- [ ] 

- [ ] @ @crypticplank

**Comment by crypticplank** [comment]
Should be fixed in theory, re-open if it is not.
