### ISSUE TITLE
READ HERE

### ISSUE THREAD

**Issue by crypticplank** [crypticplank/flappybird#30]
The server is now offline do to lack community contribution.

**Comment by 1345abozR** [comment]
- > ### 

- [ ]   #@`_**[](u
Duplicate of #
Duplicate of  

[ ] [@#rl)**_`](_url_)467AB7i
Duplicate of # @budidino @

- [ ] 

- [ ] 

> 

> [](url)

**Comment by 1345abozR** [comment]
- [ ] # @ # #31 #28 

1. ### 

- [ ]  #**

- Duplicate of 

- [ ] #678o8**

- [ ] 

> [](url)
