### ISSUE TITLE
How about making the mario at 999 score a reality? 👀

### ISSUE THREAD

**Issue by Void48** [crypticplank/flappybird#31]
This would be really cool to see https://youtu.be/YHH2101OFfI?t=63

**Comment by crypticplank** [comment]
I have actually started implementing this a while ago, but stopped due to lack of interest in the project, You can actually see mario bundled with the game ;)

**Comment by crypticplank** [comment]
![image](https://user-images.githubusercontent.com/52553007/153779153-2246db24-5133-4ecf-892f-ca86cf451e09.png)

**Comment by crypticplank** [comment]
Thats in the private repo.

**Comment by crypticplank** [comment]
Did not get around to doing this, the current source code is up to date if anyone wants to add it themself.
