### ISSUE TITLE
Version 4.2.0 is 4.0.6

### ISSUE THREAD

**Issue by c12n** [crypticplank/flappybird#35]
The latest version is 4.0.6 not 4.2.0

**Comment by NikoV5** [comment]
When I downloaded this I also got this issue. When installing 4.2.0 it kept installing 4.0.6. Then when opening the app, it would prompt me to go to GitHub and download the latest version but that's what I was doing in the first place

**Comment by NikoV5** [comment]
> The latest version is 4.0.6 not 4.2.0

If this is the case, why does it say the latest version is 4.2.0?

**Comment by crypticplank** [comment]
Fixed 4.2.1 and up
