### ISSUE TITLE
Add current version label in the app

### ISSUE THREAD

**Issue by NikoV5** [crypticplank/flappybird#36]
Is there anyway to add the current version of the app in the settings menu? Not really a big request but it is helpful to see what version of the app you are on.

**Comment by crypticplank** [comment]
I will work on it :)

**Comment by crypticplank** [comment]
![Simulator Screen Shot - iPhone 11 - 2022-06-11 at 18 34 34](https://user-images.githubusercontent.com/52553007/173207022-54ef2d16-5581-445c-8e38-5fdbc690f4dc.png)
Like this?

**Comment by crypticplank** [comment]
4.2.2 Added

**Comment by NikoV5** [comment]
Yes! Thank you 🙏🏼
