### ISSUE TITLE
Latest version is saying I need to update

### ISSUE THREAD

**Issue by burkybang** [crypticplank/flappybird#37]
I’m on 4.2.2, which is currently the latest, but the app is saying I need to update.

![04CDECF5-DCAD-4F9A-86E0-E07C52837559](https://user-images.githubusercontent.com/927886/173209370-3d9d565f-5da5-4d8d-9a22-16f62f3bb750.jpeg)

![A0B4CC1D-4314-4A22-BB11-0E7A03046B86](https://user-images.githubusercontent.com/927886/173209338-50150848-2fcd-4bbe-8fdd-55ad5caecf58.png)

**Comment by crypticplank** [comment]
That definitly should not be doing that, give me a moment

**Comment by burkybang** [comment]
Never mind. I was expecting it to install over my existing installation, but it actually installed a new one, so I was still opening the old one until I noticed I now had two.

**Comment by crypticplank** [comment]
Oh ok :) Glad to help anytime :)

**Comment by crypticplank** [comment]
Yeah, i changed the bundle identifier to the really old one.

**Comment by burkybang** [comment]
Makes sense. Side note, is your jailbreak repo down?

https://repo.brandonplank.org/
